# Generated by Django 3.2.6 on 2021-08-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charts',
            options={'verbose_name_plural': 'chart'},
        ),
    ]
