# Generated by Django 3.2.6 on 2021-08-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_alter_charts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charts',
            options={'ordering': ['id'], 'verbose_name_plural': 'chart'},
        ),
    ]
